# Generated by Django 4.2.1 on 2024-01-09 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_coach_citizenship'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coach',
            options={'ordering': ['id'], 'verbose_name': 'Тренер', 'verbose_name_plural': 'Тренеры'},
        ),
        migrations.AddIndex(
            model_name='coach',
            index=models.Index(fields=['name'], name='clubs_coach_name_f21dc1_idx'),
        ),
    ]
