# Generated by Django 4.2.1 on 2024-01-09 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0004_alter_coach_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coach',
            name='age',
        ),
        migrations.AddField(
            model_name='coach',
            name='date_birth',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Birth day'),
        ),
    ]
