# Generated by Django 4.2.1 on 2024-01-09 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0005_remove_coach_age_coach_date_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='date_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Birth day'),
        ),
    ]
