# Generated by Django 4.2.1 on 2024-01-09 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0006_alter_coach_date_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubs',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True, verbose_name='URL'),
        ),
    ]
