# Generated by Django 4.2.1 on 2024-01-13 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0007_alter_clubs_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tagclub',
            options={'ordering': ['id'], 'verbose_name': 'Тэг', 'verbose_name_plural': 'Тэги'},
        ),
        migrations.AddIndex(
            model_name='tagclub',
            index=models.Index(fields=['tag'], name='clubs_tagcl_tag_9d11d7_idx'),
        ),
    ]
