# Generated by Django 4.2.1 on 2024-01-13 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0008_alter_tagclub_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coach',
            options={'ordering': ['name'], 'verbose_name': 'Тренер', 'verbose_name_plural': 'Тренеры'},
        ),
    ]
