# Generated by Django 4.2.1 on 2024-01-03 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0009_uploadfiles_alter_clubs_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubs',
            name='logo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='logos/%Y/%m/%d/', verbose_name='Logo'),
        ),
    ]
