# Generated by Django 4.2.1 on 2024-01-06 18:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clubs', '0010_clubs_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubs',
            name='author',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clubs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clubs',
            name='content',
            field=models.TextField(blank=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='clubs',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clubs', to='clubs.country', verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='clubs',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Time_create'),
        ),
        migrations.AlterField(
            model_name='clubs',
            name='time_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Time_update'),
        ),
        migrations.AlterField(
            model_name='clubs',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
    ]
